# Generated by Django 3.0.4 on 2020-07-29 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0002_auto_20200629_0556'),
        ('warehouse', '0006_auto_20200228_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vendor.Vendor'),
        ),
    ]
