# Generated by Django 3.0.4 on 2021-01-20 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0004_vendor_homepage_collection'),
        ('checkout', '0025_auto_20200221_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutline',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.Vendor'),
        ),
    ]
