# Generated by Django 3.0.4 on 2020-04-07 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0115_auto_20200221_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantVendorListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='listing', to='product.ProductVariant')),
            ],
        ),
    ]
