# Generated by Django 3.0.4 on 2020-04-07 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0116_productvariantvendorlisting'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantvendorlisting',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='listing', to='vendor.Vendor'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='vendors',
            field=models.ManyToManyField(related_name='products', through='product.ProductVariantVendorListing', to='vendor.Vendor'),
        ),
    ]
