# Generated by Django 3.0.4 on 2020-04-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('product', '0117_auto_20200407_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='vendors',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', through='product.ProductVariantVendorListing', to='vendor.Vendor'),
        ),
    ]
